### ISSUE TITLE
Can't install can't work

### ISSUE THREAD

**Issue by bigzhu** [weirongxu/coc-explorer#116]
<img width="578" alt="Screen Shot 2020-02-25 at 10 19 13 AM" src="https://user-images.githubusercontent.com/489815/75209092-59c67a00-57b8-11ea-8335-92ffcb9bf67a.png">

Seemly some wrong with the project.
The install will take a very long time...

**Comment by weirongxu** [comment]
How did you install `coc-explorer`? Please provide the content of `:CocInfo`.

**Comment by bigzhu** [comment]
```

## versions

vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.74-bcdd8cdfca
term: iTerm.app
platform: darwin

## Messages

## Output channel: git
Looking for git in: git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
resolved root: /Users/bigzhu/english_buoy
resolved root: /Users/bigzhu/english_buoy
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/bigzhu/english_buoy
resolved root: /Users/bigzhu/english_buoy
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/bigzhu/english_buoy
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/bigzhu/english_buoy
resolved root: /Users/bigzhu/english_buoy
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/bigzhu/english_buoy
resolved root: /Users/bigzhu/english_buoy
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/bigzhu/english_buoy
resolved root: /Users/bigzhu/english_buoy
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard


## Output channel: prettier


## Output channel: highlight
[Info  - 2:59:49 PM] Highlight server running in node v12.16.1


```

**Comment by weirongxu** [comment]
This project requires `open` and `trash`, and these two modules cannot be packaged with `webpack`. Its dependency tree is very deep, and download using the China network may fail.

**Comment by weirongxu** [comment]
Maybe you can try to use the npm mirror
http://npm.taobao.org/

**Comment by bigzhu** [comment]
I use the good proxy successfully install and use coc-explorer before.
suddenly coc nvim auto-update plugin makes coc-explorer don't work, I think it does not because of my network.

already try to use http://npm.taobao.org/ before the same error still no work.

**Comment by weirongxu** [comment]
Please provide the content of `:CocOpenLog`.

**Comment by weirongxu** [comment]
And also the file list inside ~/.config/coc/extensions/node_modules/coc-explorer/node_modules

**Comment by bigzhu** [comment]
`:CocOpenLog`:
```
2020-02-26T10:27:07.047 INFO (pid:52543) [services] - registered service "highlight"
2020-02-26T10:27:07.146 INFO (pid:52543) [plugin] - coc 0.0.74-bcdd8cdfca initialized with node: v12.16.1
2020-02-26T10:27:07.152 INFO (pid:52543) [language-client-index] - highlight started with 52545
2020-02-26T10:27:07.159 INFO (pid:52543) [model-extension] - Using npm from: /usr/local/bin/npm
2020-02-26T10:27:07.160 INFO (pid:52543) [model-extension] - Loading info of coc-explorer.
2020-02-26T10:27:07.163 INFO (pid:52543) [model-fetch] - fetch: https://registry.npmjs.org/coc-explorer
2020-02-26T10:27:07.164 INFO (pid:52543) [model-fetch] - Using proxy from: 127.0.0.1:1087
2020-02-26T10:27:07.240 INFO (pid:52543) [services] - highlight server state change: starting => running
2020-02-26T10:27:07.998 INFO (pid:52543) [model-extension] - Downloading from https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.3.5.tgz
2020-02-26T10:27:07.999 INFO (pid:52543) [model-fetch] - Using proxy from: 127.0.0.1:1087
2020-02-26T10:27:09.086 INFO (pid:52543) [model-extension] - Installing dependencies.
2020-02-26T10:28:02.999 INFO (pid:52543) [model-extension] - Moving to new folder.
2020-02-26T10:28:03.001 INFO (pid:52543) [model-extension] - Installed extension: coc-explorer
2020-02-26T10:28:03.030 ERROR (pid:52543) [extensions] - Error: Cannot find module 'trash'
Require stack:
- /Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js
- /Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at req (/Users/bigzhu/.config/nvim/plugged/coc.nvim/build/index.js:49117:21)
    at Object.<anonymous> (/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:182663)
    at n (/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:220)
    at Object.<anonymous> (/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:165762)
    at n (/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:220)
    at Object.<anonymous> (/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:2455)
    at n (/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:220) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js',
    '/Users/bigzhu/.config/coc/extensions/node_modules/coc-explorer/lib/index.js'
  ]
}
```

**Comment by bigzhu** [comment]
Sorry to bother you.
It is my local npm problem.
When I remove `coc/extensions/node_modules/coc-explorer` and run `npm cache clean --force` then reinstall coc-explorer everything is working fine.
thanks for your help.

**Comment by freak-harsh** [comment]
will any one help me.
im geting this     ` ✗ coc-explorer /usr/bin/npm install exited with 254`
while typing command :      `  :CocInstall coc-explorer`

**Comment by weirongxu** [comment]
> will any one help me.
> im geting this ` ✗ coc-explorer /usr/bin/npm install exited with 254`
> while typing command : ` :CocInstall coc-explorer`

You should google npm's 254 related issues
