### ISSUE TITLE
[coc.nvim] TypeError: Cannot read property 'directory' of undefined

### ISSUE THREAD

**Issue by cjnucette** [weirongxu/coc-explorer#132]
I getting this error message every time I try to open a file (hitting enter on the selected file).

CocInfo:
```vim
## Messages
[coc.nvim] TypeError: Cannot read property 'directory' of undefined
[coc.nvim] TypeError: Cannot read property 'directory' of undefined
## Output channel: explorer
 
TypeError: Cannot read property 'directory' of undefined
    at /home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:366138
    at Object.callback (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:30181)
    at b.doAction (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:30619)
    at v.doActions (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:290026)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:289009)
    at async Immediate.<anonymous> (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:110651)
TypeError: Cannot read property 'directory' of undefined
    at /home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:366138
    at Object.callback (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:30181)
    at b.doAction (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:30619)
    at v.doActions (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:290026)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:289009)
    at async Immediate.<anonymous> (/home/cjnucette/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:9:110651)
```
init.vim:
```vim
set runtimepath^=~/.config/nvim/plugged/coc.nvim
set runtimepath^=~/.config/nvim/plugged/onedark
filetype plugin indent on
syntax on
set hidden

```

**Comment by bfulop** [comment]
I have the same issue, since that last update to `coc-explorer`.

My workaround until a we have a fix is to press `y` to copy the file path, close `coc-explorer` and open the file with `:e [paste]`
