### ISSUE TITLE
Invalid window ID

### ISSUE THREAD

**Issue by AdamBD** [weirongxu/coc-explorer#211]
Running into the following error when opening files from coc.explorer

## Output channel: explorer
Error: request error nvim_win_close - Invalid window id
    at /Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at DecodeStream.Readable.push (_stream_readable.js:217:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:12757:12)

**Comment by weirongxu** [comment]
Can't reproduce, please update `coc.nvim` and `coc-explorer` to the latest version, and provide reproduction steps
