### ISSUE TITLE
"BufWinLeave" error when trying to use `f` command

### ISSUE THREAD

**Issue by macintacos** [weirongxu/coc-explorer#274]
I'm getting the following error when I try to use `f` in the `coc-explorer` buffer:

```
[coc.nvim]: Error on BufWinLeave: Cannot read property 'shown' of undefined
TypeError: Cannot read property 'shown' of undefined
    at /Users/juliant/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:88954
    at /Users/juliant/.config/vim-plug/coc.nvim/build/index.js:16565:45
    at new Promise (<anonymous>)
    at wrappedhandler (/Users/juliant/.config/vim-plug/coc.nvim/build/index.js:16562:42)
    at /Users/juliant/.config/vim-plug/coc.nvim/build/index.js:16539:49
    at Array.map (<anonymous>)
    at Events.fire (/Users/juliant/.config/vim-plug/coc.nvim/build/index.js:16539:39)
    at NeovimClient.<anonymous> (/Users/juliant/.config/vim-plug/coc.nvim/build/index.js:11580:40)
    at NeovimClient.emit (events.js:210:5)
    at NeovimClient.emitNotification (/Users/juliant/.config/vim-plug/coc.nvim/build/index.js:11894:18)
```

Can't really tell what's going on here, but it happens every single time without fail.

**Comment by macintacos** [comment]
Ah, ran `:CocUpdate` and it seems to be resolved now. Closing!
