### ISSUE TITLE
Startup Errors in Missing Folder

### ISSUE THREAD

**Issue by PhilRunninger** [weirongxu/coc-explorer#289]
This is definitely an edge case, one I'd say is not that important.

I noticed it in Neovim on my Mac, but I suspect it will occur in other OSes and with Vim.

If you start Neovim in the terminal while in a directory that doesn't exist, you get the error messages shown below. How is this possible, you ask? Here's one way:
```
~/.vim $ mkdir foobar; cd foobar
~/.vim/foobar $ bash
~/.vim/foobar $ cd ..
~/.vim $ rmdir foobar
~/.vim $ exit
~/.vim/foobar $ nvim
```
Here are the error messages that show up in Neovim:
```
[coc.nvim]: internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at process.cwd (/Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim/node_modules/graceful-fs/po
lyfills.js:10:19)
    at new Workspace (/Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim/lib/workspace.js:51:29)
    at Object.<anonymous> (/Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim/lib/workspace.js:184
3:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
Error on request (extensionStats): Vim(return):Error invoking 'extensionStats' on channel 3:
ch 3 was closed by the client
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
E712: Argument of map() must be a List or Dictionary
```

**Comment by weirongxu** [comment]
Thank you for pointing out this issue, but actually, this should be a bug of coc.nvim

**Comment by PhilRunninger** [comment]
@weirongxu, thanks for correcting me. I should have figured that out myself. I'll create a new issue in coc.nvim, if not already there.

**Comment by PhilRunninger** [comment]
New issue in coc.nvim: https://github.com/neoclide/coc.nvim/issues/2483
