### ISSUE TITLE
Error when cancel coc-list

### ISSUE THREAD

**Issue by iamcco** [weirongxu/coc-explorer#308]
Reproduce:

1. `:CocList`
2. type `Esc` cancel list

```

年糕小豆汤 @iamcco 16:31
## versions

vim version: NVIM v0.5.0-nightly-704-g90f3a8ba2
node version: v10.19.0
coc.nvim version: 0.0.79-f0e68fbf29
coc.nvim directory: /Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim
term: xterm-kitty
platform: darwin

## Log of coc.nvim

2020-11-10T16:29:22.174 WARN (pid:66846) [attach] - Plugin not ready when received "highlight" []
2020-11-10T16:29:22.405 INFO (pid:66846) [services] - registered service "languageserver.sh"
2020-11-10T16:29:22.406 INFO (pid:66846) [services] - registered service "languageserver.dockerfile"
2020-11-10T16:29:22.406 INFO (pid:66846) [services] - registered service "languageserver.ccls"
2020-11-10T16:29:22.406 INFO (pid:66846) [services] - registered service "languageserver.golang"
2020-11-10T16:29:22.659 INFO (pid:66846) [services] - registered service "diagnostic-languageserver"
2020-11-10T16:29:22.723 INFO (pid:66846) [services] - registered service "eslint"
2020-11-10T16:29:23.060 INFO (pid:66846) [language-client-index] - cSpell started with 66848
2020-11-10T16:29:23.079 INFO (pid:66846) [watchman] - watchman watching project: /Users/yuuko/development/coc-flutter
2020-11-10T16:29:23.312 INFO (pid:66846) [services] - registered service "highlight"
2020-11-10T16:29:23.742 INFO (pid:66846) [coc-imselect] - Observer for input change started
2020-11-10T16:29:25.314 INFO (pid:66846) [language-client-index] - highlight started with 66851
2020-11-10T16:29:26.490 INFO (pid:66846) [plugin] - coc.nvim 0.0.79-f0e68fbf29 initialized with node: v10.19.0 after 4298ms
2020-11-10T16:29:29.232 ERROR (pid:66846) [node-client] - request error on "nvim_buf_get_option" [ 'modified' ] Invalid buffer id: 2 Error
    at Buffer.request (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:15462:21)
    at Buffer.getOption (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:15506:21)
    at s.onEvent (/Users/yuuko/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:19:228233)
    at /Users/yuuko/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:19:216326
    at Promise (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:16573:45)
    at new Promise (<anonymous>)
    at wrappedhandler (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:16570:42)
    at Promise.all.cbs.map.fn (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:16547:49)
    at Array.map (<anonymous>)
    at Events.fire (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:16547:39)
    at NeovimClient.nvim.on (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:11582:40)
    at NeovimClient.emit (events.js:198:13)
    at NeovimClient.emitNotification (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:11897:18)
    at NeovimClient.handleNotification (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:11901:14)
    at NvimTransport.emit (events.js:198:13)
    at NvimTransport.parseMessage (/Users/yuuko/.configrc/nvim/viml/plugins/coc.nvim/build/index.js:12096:18)
```

**Comment by iamcco** [comment]
Seems still have the problem.

Reproduce:

1. `:CocList`
2. type `Esc` cancel list
3. `:CocList` reopen list and throw error message.

**Comment by weirongxu** [comment]
The last patch still have the error message in `CocInfo`, it should be fixed now
