### ISSUE TITLE
All keymappings stopped working

### ISSUE THREAD

**Issue by Liquidmantis** [weirongxu/coc-explorer#310]
For some reason my keymappings no longer work, even the defaults.  This happened after an update, and I've changed `explorer.keyMappings` to `explorer.keyMappings.global`, but no luck.  Am I missing something obvious?

**Comment by weirongxu** [comment]
Check the `verbose map <buffer>` in the coc-explorer buffer, and provide your `:CocInfo`.

**Comment by weirongxu** [comment]
Also, try to reproduce it in minimal vimrc

**Comment by Liquidmantis** [comment]
Yeah, I've stripped my vimrc down to just loading CoC, and uninstall all other plugins other the coc-explorer.

CocInfo:
```
## versions

vim version: NVIM v0.5.0-nightly-209-g27d630926
node version: v15.2.0
coc.nvim version: 0.0.79
coc.nvim directory: /Users/liquid/.vim/plugged/coc.nvim
term: xterm-256color
platform: darwin

## Output channel: coc-helper

declare fn 1_util.global_cursor_position
declare fn 1_util.is_float
declare fn 1_util.close_win_by_bufnr
declare fn 1_util.run_coc_cmd
declare fn 1_util.run_coc_cmd_async
declare fn 2_events.activate
declare fn 2_events.deactivate
declare fn 2_events.do_autocmd
declare fn 3_buf.create_by_name
declare fn 3_buf.create
declare fn 4_float.init_execute
declare fn 4_float.open_win
declare fn 4_float.create
declare fn 4_float.open
declare fn 4_float.resume
declare fn 4_float.update
declare fn 4_float.winid
declare fn 4_float.border_winid
declare fn 4_float.close
call 2_events.activate
call 2_events.activate

## Output channel: explorer
```

I'm running nvim from head, but also totally uninstalled and installed 0.4.4 stable but it's the same behavior.

`CocOpenLog` shows this error a lot:
```
2020-11-14T11:40:27.310 INFO (pid:45215) [plugin] - coc.nvim 0.0.79 initialized with node: v15.2.0 after 150ms
2020-11-14T11:40:33.385 ERROR (pid:45215) [workspace] - Error on create buffer: Error: request error nvim_call_function - Vim:E119: Not enough arguments for function: coc#util#get_bufoptions
    at /Users/liquid/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:40:32
    at /Users/liquid/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:116:13
    at NvimTransport.parseMessage (/Users/liquid/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:57:17)
    at DecodeStream.<anonymous> (/Users/liquid/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:27:18)
    at DecodeStream.emit (node:events:329:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at DecodeStream.Readable.push (node:internal/streams/readable:218:10)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/liquid/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
    at DecodeBuffer.flush (/Users/liquid/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/flex-buffer.js:57:12)
    at DecodeStream._transform (/Users/liquid/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:30:16)
    at DecodeStream.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:388:12)
    at DecodeStream.Writable.write (node:internal/streams/writable:333:10)
    at Buffered.ondata (node:internal/streams/readable:715:22)
    at Buffered.emit (node:events:329:20)
```

**Comment by weirongxu** [comment]
Can you try this mini_vimrc? https://github.com/weirongxu/coc-explorer/tree/master/mini_vimrc

```
nvim -u mini.vim
```

**Comment by Liquidmantis** [comment]
Sorry, I haven't had a chance to work on this.  I just cloned the repo and tried using that mini.vim, but then I don't have CoC enabled and have no access to coc-explorer.

**Comment by weirongxu** [comment]
You can modify the coc.nvim directory to your local coc.nvim runtime directory, then remove coc-explorer runtime, and use `CocInstall` to install this extension

**Comment by Liquidmantis** [comment]
Thanks.  Well, I poked around some more and just renamed my ~/.vim directory and did a fresh plugin install.  Now I'm back up and running fine, and that create buffer error from above isn't appearing in my CoC log.

Sorry for the trouble.  It is SO nice to be fixed up!  CoC-explorer is an integral part of my workflow.

**Comment by AndreSouzaAbreu** [comment]
I was having the same issue after migrating from vim to neovim. I found that the reason was that the `coc-setttings.json` should
be under `.config/nvim/`. Previously the file was not there because I wasn't using nvim
