### ISSUE TITLE
Failed to open explorer, [coc.nvim] TypeError: Cannot use 'in' operator to search for 'getDimension' in undefined

### ISSUE THREAD

**Issue by lastingman** [weirongxu/coc-explorer#336]
![image](https://user-images.githubusercontent.com/10057502/102175494-a3fd2100-3eda-11eb-9d2f-fe772ec2fad0.png)

**Comment by weirongxu** [comment]
Upgrade your coc.nvim to latest?

**Comment by lastingman** [comment]
> Upgrade your coc.nvim to latest?

This happens after I upgrade plugins.

**Comment by weirongxu** [comment]
Can't reproduce, please update `coc-explorer` to the latest version and provide output of `CocInfo` and `CocOpenLog`

**Comment by lastingman** [comment]
```
  1   ## versions
    1
    2 vim version: NVIM v0.5.0-dev+nightly
    3 node version: v14.15.1
    4 coc.nvim version: 0.0.79-437fdaadab
    5 coc.nvim directory: /Users/like/.config/nvim/plugged/coc.nvim
    6 term: iTerm.app
    7 platform: darwin
    8
    9 ## Log of coc.nvim
   10
   11 2020-12-15T17:21:11.295 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-tsserver", "coc-tsserver" already global extension.
   12 2020-12-15T17:21:11.298 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-prettier", "coc-prettier" already global extension.
   13 2020-12-15T17:21:11.298 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-emmet", "coc-emmet" already global extension.
   14 2020-12-15T17:21:11.298 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-css", "coc-css" already global extension.
   15 2020-12-15T17:21:11.298 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-json", "coc-json" already global extension.
   16 2020-12-15T17:21:11.298 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-yaml", "coc-yaml" already global extension.
   17 2020-12-15T17:21:11.299 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-explorer", "coc-explorer" already global extension.
   18 2020-12-15T17:21:11.299 INFO (pid:61202) [extensions] - Skipped load vim plugin from "/Users/like/.config/nvim/plugged/coc-yank", "coc-yank" already global extension.
   19 2020-12-15T17:21:11.852 INFO (pid:61202) [services] - registered service "eslint"
   20 2020-12-15T17:21:11.858 INFO (pid:61202) [plugin] - coc.nvim 0.0.79-437fdaadab initialized with node: v14.15.1 after 631ms
   21 2020-12-15T17:21:11.868 INFO (pid:61202) [watchman] - watchman watching project: /Users/like/.config/nvim/plugged/coc-explorer
   22 2020-12-15T17:21:11.997 INFO (pid:61202) [coc-imselect] - Observer for input change started
   23 2020-12-15T17:21:12.283 ERROR (pid:61202) [coc-explorer] - TypeError: Cannot use 'in' operator to search for 'getDimension' in undefined
   24     at new t.FloatingPreview (/Users/like/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:19:216944)
   25     at new m (/Users/like/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:19:203199)
   26     at Function.create (/Users/like/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:19:207962)
   27     at processTicksAndRejections (internal/process/task_queues.js:93:5)
   28     at async t.ExplorerManager.open (/Users/like/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:19:202353)
   29 2020-12-15T17:21:24.268 WARN (pid:61202) [model-menu] - Ignored key press: <C-j>
```

把 `/Users/like/.config/coc` 删了，重新 update 了一下就好了。

**Comment by wookayin** [comment]
I ran into this error, updated the plugin (`:CocUpdate`) and the bug was gone.
