### ISSUE TITLE
[question]cannot open a file with key stroke

### ISSUE THREAD

**Issue by yyb196** [weirongxu/coc-explorer#363]
Greate plugin, I have use this plugin normally for a long time, but recently I run into a problem, After open coc-explorer,
 if i press 'o' or 'O' or 'n' it will spit out "E21: Cannot make changes, 'modifiable' is off"
 if I press '?' it will apear at the bottom command line.

![image](https://user-images.githubusercontent.com/1502577/104186533-8081b380-5451-11eb-8a11-1aefddd545d7.png)

how to find out what' wrong?

**Comment by weirongxu** [comment]
Please provide the reproduced configuration, vim version, and output of `:CocOpenLog`

**Comment by yyb196** [comment]
Thanks for your instant reply. @weirongxu 

vim configuration:
```
" using coc.nvim
let g:coc_global_extensions = ['coc-python', 'coc-vimlsp', 'coc-html', 'coc-json', 'coc-css', 'coc-tsserver', 'coc-snippets', 'coc-yank'       , 'coc-gitignore', 'coc-vimlsp', 'coc-stylelint', 'coc-tslint', 'coc-lists', 'coc-git', 'coc-explorer', 'coc-pyright', 'coc-sourcekit',        'coc-translator', 'coc-flutter', 'coc-todolist', 'coc-yaml', 'coc-tasks', 'coc-actions', 'coc-diagnostic', 'coc-prettier', 'coc-syntax',        'coc-eslint']

nmap tt :CocCommand explorer<CR>
```

CocInfo:
```
vim version: NVIM v0.4.3
  node version: v12.18.0
  coc.nvim version: 0.0.80-fff2a86b16
  coc.nvim directory: /home/yyb/.config/nvim/plugged/coc.nvim
  term: xterm
  platform: linux
```

CocOpenLog:
```
                                                    │
  2021-01-12T10:20:23.905 INFO (pid:59891) [attach] - receive notification: jumpImplementation []                                            │
  2021-01-12T10:20:27.159 INFO (pid:59891) [attach] - receive notification: runCommand [ 'explorer' ]                                        │
  2021-01-12T10:20:27.178 INFO (pid:59891) [attach] - receive request: doAutocmd [ 2 ]                                                       │
  2021-01-12T10:20:27.179 ERROR (pid:59891) [node-client] - request error on "nvim_call_function" [ 'coc#util#clear_pos_matches', [ '^Highlig│
  htedyankRegion' ] ] Vim:E117: Unknown function: coc#util#clear_pos_matches Error                                                           │
      at rM.request (/home/yyb/.config/nvim/plugged/coc.nvim/build/index.js:20:34439)                                               │
      at rM.call (/home/yyb/.config/nvim/plugged/coc.nvim/build/index.js:22:6259)                                                   │
      at Object.<anonymous> (/home/yyb/.config/coc/extensions/node_modules/coc-yank/lib/index.js:133:53)                            │
      at Generator.next (<anonymous>)                                                                                                        │
      at /home/yyb/.config/coc/extensions/node_modules/coc-yank/lib/index.js:98:71                                                  │
      at new Promise (<anonymous>)                                                                                                           │
      at __awaiter (/home/yyb/.config/coc/extensions/node_modules/coc-yank/lib/index.js:94:12)                                      │
      at callback (/home/yyb/.config/coc/extensions/node_modules/coc-yank/lib/index.js:131:29)                                      │
      at /home/yyb/.config/nvim/plugged/coc.nvim/build/index.js:253:3004                                                            │
      at MP.cocAction (/home/yyb/.config/nvim/plugged/coc.nvim/build/index.js:254:6418)                                             │
  2021-01-12T10:20:27.180 INFO (pid:59891) [attach] - receive notification: highlight []                                                     │
  2021-01-12T10:20:27.191 INFO (pid:59891) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 6 │
  ]                                                                                                                                          │
  2021-01-12T10:20:27.192 INFO (pid:59891) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 6 │
  ]
```

**Comment by weirongxu** [comment]
I tried these extensions, but still can't reproduce. It may be a conflict with other plugins or configurations. can you try the mini_vimrc?

clone repository, then execute
```
yarn
cd mini_vimrc
nvim -u mini.vim
```

**Comment by yyb196** [comment]
I change to another machine it works, I have no idea what was happening, close this issue anyway, thanks for your help again @weirongxu .

**Comment by weirongxu** [comment]
> I change to another machine it works, I have no idea what was happening, close this issue anyway, thanks for your help again @weirongxu .

Maybe you need to clean coc extensions cache
