### ISSUE TITLE
[coc.nvim] Command: explorer not found

### ISSUE THREAD

**Issue by jose4125** [weirongxu/coc-explorer#369]
I updated all the coc extensions. after the updates ended the extension stopped working. I'm getting [coc.nvim] Command: explorer not found, before this update it was working.

**Comment by weirongxu** [comment]
Try to upgrade coc.nvim and reinstall coc-explorer, if there are still no working, please upload the installed `CocOpenLog`

**Comment by jose4125** [comment]
I upgraded the coc.nvim and reinstalled coc-explorer but is not working. runing `CocOpenLog` I got

```
2021-01-18T19:46:14.026 ERROR (pid:51140) [extensions] - Error on createExtension coc-explorer from /Users/jlombana/.config/coc/extensions/node_modules/coc-explorer/lib/index.js Error: Package exports for '/Users/jlombana/.config/coc/extensions/node_modules/coc-explorer/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at r (/Users/jlombana/.local/share/nvim/plugged/coc.nvim/build/index.js:224:13835)
    at Object.<anonymous> (/Users/jlombana/.config/coc/extensions/node_modules/coc-explorer/node_modules/trash/lib/linux.js:6:14)
    at Module._compile (/Users/jlombana/.local/share/nvim/plugged/coc.nvim/build/index.js:224:14154) {
  code: 'MODULE_NOT_FOUND'
}
2021-01-18T19:46:14.034 INFO (pid:51140) [services] - registered service "highlight"
2021-01-18T19:46:14.111 INFO (pid:51140) [language-client-index] - highlight started with 51164
2021-01-18T19:46:14.181 INFO (pid:51140) [services] - registered service "stylelintplus"
2021-01-18T19:46:14.224 INFO (pid:51140) [plugin] - coc.nvim 0.0.80-7c70fbf971 initialized with node: v13.1.0 after 453ms
2021-01-18T19:46:14.228 INFO (pid:51140) [language-client-index] - cSpell started with 51166
2021-01-18T19:46:16.738 INFO (pid:51140) [attach] - receive notification: runCommand [ 'explorer' ]
2021-01-18T19:46:18.124 INFO (pid:51140) [attach] - receive notification: runCommand [ 'explorer' ]
2021-01-18T19:46:18.707 INFO (pid:51140) [attach] - receive notification: runCommand [ 'explorer' ]
2021-01-18T19:46:22.893 INFO (pid:51140) [attach] - receive notification: runCommand [ 'explorer' ]
2021-01-19T09:38:40.910 INFO (pid:51140) [attach] - receive notification: doAutocmd [ 1 ]
2021-01-19T09:39:22.347 INFO (pid:51140) [attach] - receive notification: doAutocmd [ 1 ]
2021-01-19T09:40:18.546 INFO (pid:51140) [attach] - receive notification: uninstallExtension [ 'coc-explorer' ]
2021-01-19T09:40:34.772 INFO (pid:51140) [attach] - receive notification: installExtensions [ 'coc-explorer' ]
2021-01-19T09:40:34.834 INFO (pid:51140) [attach] - receive notification: doAutocmd [ 1 ]
2021-01-19T09:40:34.853 INFO (pid:51140) [model-installer] - Using npm from: /Users/jlombana/.nvm/versions/node/v13.1.0/bin/npm
2021-01-19T09:40:34.857 INFO (pid:51140) [model-installer] - Get info from https://registry.npmjs.org/
2021-01-19T09:40:36.498 INFO (pid:51140) [model-installer] - Fetched info of coc-explorer {
  'dist.tarball': 'https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.14.1.tgz',
  'engines.coc': '^0.0.75',
  version: '0.14.1',
  name: 'coc-explorer'
}
2021-01-19T09:40:36.502 INFO (pid:51140) [model-installer] - Downloading from https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.14.1.tgz
2021-01-19T09:40:36.541 INFO (pid:51140) [model-installer] - Download progress 0.4%
2021-01-19T09:40:36.546 INFO (pid:51140) [model-installer] - Download progress 1.1%
2021-01-19T09:40:36.551 INFO (pid:51140) [model-installer] - Download progress 1.8%
2021-01-19T09:40:36.552 INFO (pid:51140) [model-installer] - Download progress 2.6%
2021-01-19T09:40:36.552 INFO (pid:51140) [model-installer] - Download progress 3.3%
2021-01-19T09:40:36.553 INFO (pid:51140) [model-installer] - Download progress 4.1%
2021-01-19T09:40:36.554 INFO (pid:51140) [model-installer] - Download progress 4.8%
2021-01-19T09:40:36.554 INFO (pid:51140) [model-installer] - Download progress 5.6%
2021-01-19T09:40:36.555 INFO (pid:51140) [model-installer] - Download progress 6.3%
2021-01-19T09:40:36.555 INFO (pid:51140) [model-installer] - Download progress 7.1%
2021-01-19T09:40:36.555 INFO (pid:51140) [model-installer] - Download progress 7.8%
2021-01-19T09:40:36.557 INFO (pid:51140) [model-installer] - Download progress 8.6%
2021-01-19T09:40:36.557 INFO (pid:51140) [model-installer] - Download progress 9.3%
2021-01-19T09:40:36.558 INFO (pid:51140) [model-installer] - Download progress 10.1%
2021-01-19T09:40:36.558 INFO (pid:51140) [model-installer] - Download progress 10.8%
2021-01-19T09:40:36.558 INFO (pid:51140) [model-installer] - Download progress 11.5%
2021-01-19T09:40:36.559 INFO (pid:51140) [model-installer] - Download progress 12.3%
2021-01-19T09:40:36.559 INFO (pid:51140) [model-installer] - Download progress 13.0%
2021-01-19T09:40:36.559 INFO (pid:51140) [model-installer] - Download progress 13.7%
2021-01-19T09:40:36.559 INFO (pid:51140) [model-installer] - Download progress 14.5%
2021-01-19T09:40:36.559 INFO (pid:51140) [model-installer] - Download progress 15.2%
2021-01-19T09:40:36.560 INFO (pid:51140) [model-installer] - Download progress 16.0%
2021-01-19T09:40:36.560 INFO (pid:51140) [model-installer] - Download progress 16.7%
2021-01-19T09:40:36.560 INFO (pid:51140) [model-installer] - Download progress 17.4%
2021-01-19T09:40:36.560 INFO (pid:51140) [model-installer] - Download progress 18.2%
2021-01-19T09:40:36.560 INFO (pid:51140) [model-installer] - Download progress 18.9%
2021-01-19T09:40:36.561 INFO (pid:51140) [model-installer] - Download progress 19.7%
2021-01-19T09:40:36.561 INFO (pid:51140) [model-installer] - Download progress 20.4%
2021-01-19T09:40:36.561 INFO (pid:51140) [model-installer] - Download progress 21.2%
2021-01-19T09:40:36.561 INFO (pid:51140) [model-installer] - Download progress 21.9%
2021-01-19T09:40:36.562 INFO (pid:51140) [model-installer] - Download progress 22.7%
2021-01-19T09:40:36.562 INFO (pid:51140) [model-installer] - Download progress 23.4%
2021-01-19T09:40:36.562 INFO (pid:51140) [model-installer] - Download progress 24.2%
2021-01-19T09:40:36.562 INFO (pid:51140) [model-installer] - Download progress 24.9%
2021-01-19T09:40:36.562 INFO (pid:51140) [model-installer] - Download progress 25.6%
2021-01-19T09:40:36.563 INFO (pid:51140) [model-installer] - Download progress 26.4%
2021-01-19T09:40:36.563 INFO (pid:51140) [model-installer] - Download progress 27.1%
2021-01-19T09:40:36.563 INFO (pid:51140) [model-installer] - Download progress 27.9%
2021-01-19T09:40:36.563 INFO (pid:51140) [model-installer] - Download progress 28.6%
2021-01-19T09:40:36.563 INFO (pid:51140) [model-installer] - Download progress 29.4%
2021-01-19T09:40:36.564 INFO (pid:51140) [model-installer] - Download progress 30.1%
2021-01-19T09:40:36.564 INFO (pid:51140) [model-installer] - Download progress 30.8%
2021-01-19T09:40:36.564 INFO (pid:51140) [model-installer] - Download progress 33.1%
2021-01-19T09:40:36.564 INFO (pid:51140) [model-installer] - Download progress 35.4%
2021-01-19T09:40:36.565 INFO (pid:51140) [model-installer] - Download progress 37.7%
2021-01-19T09:40:36.565 INFO (pid:51140) [model-installer] - Download progress 40.0%
2021-01-19T09:40:36.565 INFO (pid:51140) [model-installer] - Download progress 42.3%
2021-01-19T09:40:36.565 INFO (pid:51140) [model-installer] - Download progress 44.6%
2021-01-19T09:40:36.566 INFO (pid:51140) [model-installer] - Download progress 46.9%
2021-01-19T09:40:36.566 INFO (pid:51140) [model-installer] - Download progress 48.7%
2021-01-19T09:40:36.566 INFO (pid:51140) [model-installer] - Download progress 51.0%
2021-01-19T09:40:36.566 INFO (pid:51140) [model-installer] - Download progress 53.3%
2021-01-19T09:40:36.567 INFO (pid:51140) [model-installer] - Download progress 55.6%
2021-01-19T09:40:36.567 INFO (pid:51140) [model-installer] - Download progress 57.9%
2021-01-19T09:40:36.567 INFO (pid:51140) [model-installer] - Download progress 60.2%
2021-01-19T09:40:36.568 INFO (pid:51140) [model-installer] - Download progress 62.5%
2021-01-19T09:40:36.568 INFO (pid:51140) [model-installer] - Download progress 64.8%
2021-01-19T09:40:36.568 INFO (pid:51140) [model-installer] - Download progress 66.5%
2021-01-19T09:40:36.569 INFO (pid:51140) [model-installer] - Download progress 68.8%
2021-01-19T09:40:36.569 INFO (pid:51140) [model-installer] - Download progress 71.1%
2021-01-19T09:40:36.569 INFO (pid:51140) [model-installer] - Download progress 73.4%
2021-01-19T09:40:36.570 INFO (pid:51140) [model-installer] - Download progress 75.7%
2021-01-19T09:40:36.570 INFO (pid:51140) [model-installer] - Download progress 78.0%
2021-01-19T09:40:36.571 INFO (pid:51140) [model-installer] - Download progress 80.3%
2021-01-19T09:40:36.571 INFO (pid:51140) [model-installer] - Download progress 82.6%
2021-01-19T09:40:36.571 INFO (pid:51140) [model-installer] - Download progress 84.4%
2021-01-19T09:40:36.571 INFO (pid:51140) [model-installer] - Download progress 86.7%
2021-01-19T09:40:36.572 INFO (pid:51140) [model-installer] - Download progress 89.0%
2021-01-19T09:40:36.572 INFO (pid:51140) [model-installer] - Download progress 91.3%
2021-01-19T09:40:36.573 INFO (pid:51140) [model-installer] - Download progress 93.6%
2021-01-19T09:40:36.573 INFO (pid:51140) [model-installer] - Download progress 95.9%
2021-01-19T09:40:36.573 INFO (pid:51140) [model-installer] - Download progress 98.2%
2021-01-19T09:40:36.574 INFO (pid:51140) [model-installer] - Download progress 100.0%
2021-01-19T09:40:36.575 INFO (pid:51140) [model-download] - Download completed: https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.14.1.tgz
2021-01-19T09:40:36.578 INFO (pid:51140) [model-download] - Downloaded https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.14.1.tgz => /var/folders/2l/dch8tqk13pn50d0mm3frm9c000lj_h/T/nvim6rBtfN/coc-explorer-7DWJFh
2021-01-19T09:40:36.682 INFO (pid:51140) [model-installer] - Extension download at /var/folders/2l/dch8tqk13pn50d0mm3frm9c000lj_h/T/nvim6rBtfN/coc-explorer-7DWJFh
2021-01-19T09:40:36.684 INFO (pid:51140) [model-installer] - Installing dependencies by: /Users/jlombana/.nvm/versions/node/v13.1.0/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2021-01-19T09:40:44.903 INFO (pid:51140) [model-installer] - [npm] added 63 packages from 13 contributors and audited 825 packages in 7.565s
2021-01-19T09:40:44.904 INFO (pid:51140) [model-installer] - [npm] found 0 vulnerabilities
2021-01-19T09:40:44.904 INFO (pid:51140) [model-installer] - [npm] 
2021-01-19T09:40:44.973 INFO (pid:51140) [model-installer] - Update package.json at /Users/jlombana/.config/coc/extensions/package.json
2021-01-19T09:40:44.973 INFO (pid:51140) [model-installer] - Installed extension coc-explorer@0.14.1 at /Users/jlombana/.config/coc/extensions/node_modules/coc-explorer
2021-01-19T09:40:45.040 ERROR (pid:51140) [extensions] - Error on createExtension coc-explorer from /Users/jlombana/.config/coc/extensions/node_modules/coc-explorer/lib/index.js Error: Package exports for '/Users/jlombana/.config/coc/extensions/node_modules/coc-explorer/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at r (/Users/jlombana/.local/share/nvim/plugged/coc.nvim/build/index.js:224:13835)
    at Object.<anonymous> (/Users/jlombana/.config/coc/extensions/node_modules/coc-explorer/node_modules/trash/lib/linux.js:6:14)
    at Module._compile (/Users/jlombana/.local/share/nvim/plugged/coc.nvim/build/index.js:224:14154) {
  code: 'MODULE_NOT_FOUND'
}
2021-01-19T09:40:59.419 INFO (pid:51140) [attach] - receive notification: doAutocmd [ 1 ]
2021-01-19T09:41:02.844 INFO (pid:51140) [attach] - receive notification: runCommand [ 'explorer' ]
2021-01-19T09:41:40.393 INFO (pid:51140) [attach] - receive notification: openLog []
```

**Comment by weirongxu** [comment]
Looks like some module miss from your node_modules,  try to clear the npm cache

```
npm cache clean --force
```

**Comment by ayushsherpa111** [comment]
after clearing cache and doing a `git pull` on coc.vim it seemed to have fixed itself.

**Comment by svanharmelen** [comment]
I have the same issue, but a slightly different log output:

```
2021-02-02T11:27:17.439 ERROR (pid:24804) [extensions] - Error on createExtension coc-explorer from /Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js Error: Cannot find module 'vscode-languageserver-protocol'
Require stack:
- /Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js
- /Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at r (/Users/svanharmelen/.config/nvim/plugged/coc.nvim/build/index.js:224:13835)
    at Object.<anonymous> (/Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:301:1045)
    at Module._compile (/Users/svanharmelen/.config/nvim/plugged/coc.nvim/build/index.js:224:14154)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js',
    '/Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js'
  ]
}
2021-02-02T11:27:17.457 INFO (pid:24804) [plugin] - coc.nvim 0.0.80-6e5a2aaeb5 initialized with node: v15.7.0 after 154ms
2021-02-02T11:27:18.288 INFO (pid:24804) [attach] - receive notification: runCommand [ 'explorer' ]

```

Did already try to uninstall all CoC parts and clear the npm cache, but didn't make any difference...

**Comment by weirongxu** [comment]
> I have the same issue, but a slightly different log output:
> 
> ```
> 2021-02-02T11:27:17.439 ERROR (pid:24804) [extensions] - Error on createExtension coc-explorer from /Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js Error: Cannot find module 'vscode-languageserver-protocol'
> Require stack:
> - /Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js
> - /Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
>     at Module.require (node:internal/modules/cjs/loader:997:19)
>     at r (/Users/svanharmelen/.config/nvim/plugged/coc.nvim/build/index.js:224:13835)
>     at Object.<anonymous> (/Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:301:1045)
>     at Module._compile (/Users/svanharmelen/.config/nvim/plugged/coc.nvim/build/index.js:224:14154)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
>     at Module.load (node:internal/modules/cjs/loader:973:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at Module.require (node:internal/modules/cjs/loader:997:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js',
>     '/Users/svanharmelen/.config/coc/extensions/node_modules/coc-explorer/lib/index.js'
>   ]
> }
> 2021-02-02T11:27:17.457 INFO (pid:24804) [plugin] - coc.nvim 0.0.80-6e5a2aaeb5 initialized with node: v15.7.0 after 154ms
> 2021-02-02T11:27:18.288 INFO (pid:24804) [attach] - receive notification: runCommand [ 'explorer' ]
> ```
> 
> Did already try to uninstall all CoC parts and clear the npm cache, but didn't make any difference...

Should be fixed on v0.15.5 @svanharmelen

**Comment by svanharmelen** [comment]
Yes, works again using v0.15.5 Thanks for the quick fix!

**Comment by jose4125** [comment]
Updated to v0.15.6, is working, thanks
