### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by wookayin** [weirongxu/coc-explorer#394]
When the coc-explorer window gets focus, it throws an error:
```
Error on request (doKeymap): Vim(return):Error invoking 'doKeymap' on channel 3 (coc):   
Cannot read property 'startsWith' of undefined
```

coc.nvim and coc-explorer are latest.

coc-explorer 0.15.6

CocInfo:

```
 ## versions                                                                               
                                                                                           
 vim version: NVIM v0.5.0-dev+1012-gfe1ebea33                                              
 node version: v13.12.0                                                                    
 coc.nvim version: 0.0.80-b295e25867                                                       
 coc.nvim directory: $HOME/.dotfiles/vim/plugged/coc.nvim    
 term: xterm-256color                                                                      
 platform: linux                                                                           
```

```
2021-02-23T13:02:21.267 INFO (pid:330214) [attach] - receive request: doKeymap [ 'explorer-action-n-r' ]                                                           
2021-02-23T13:02:21.268 ERROR (pid:330214) [plugin] - keymap for explorer-action-n-r not found                                                                     
2021-02-23T13:02:21.268 ERROR (pid:330214) [attach] - Request error: doKeymap [ 'explorer-action-n-r' ] TypeError: Cannot read property 'startsWith' of undefined  
  ¦ at $HOME/.dotfiles/vim/plugged/coc.nvim/build/index.js:247:3883                                                                  
  ¦ at OP.cocAction ($HOME/vim/plugged/coc.nvim/build/index.js:247:11197)                                                  
  ¦ at eM.<anonymous> ($HOME/.dotfiles/vim/plugged/coc.nvim/build/index.js:129:13126)                                                
  ¦ at eM.emit (events.js:315:20)                                                                                                                                  
  ¦ at eM.handleRequest ($HOME/.dotfiles/vim/plugged/coc.nvim/build/index.js:23:2347)                                                
  ¦ at UL.emit (events.js:315:20)                                                                                                                                  
  ¦ at UL.parseMessage ($HOME/.dotfiles/vim/plugged/coc.nvim/build/index.js:21:2886)                                                 
  ¦ at Bc.<anonymous> ($HOME/.dotfiles/vim/plugged/coc.nvim/build/index.js:21:2738)                                                  
  ¦ at Bc.emit (events.js:315:20)                                                                                                                                  
  ¦ at addChunk (_stream_readable.js:297:12)
```

**Comment by weirongxu** [comment]
What is your coc-explorer related configuration? And what action is `r` key mapped to?

**Comment by wookayin** [comment]
Forgot to post the coc-explorer related configuration. It is mapped to `refresh`.

```
"explorer.keyMappings.global": {
¦ "l": "expand",
¦ "L": "expandRecursive",
¦ "H": "collapseRecursive",
¦ "I": "toggleHidden",
¦ "r": "refresh",
¦ "R": "refresh",

¦ // do not use expandable{Prev,Next}
¦ "gk": false, "gj": false,

¦ "<cr>": ["expandable?", ["expanded?", "collapse", "expand"], "open"],
¦ "<c-v>": "open:vsplit",
¦ "<c-x>": "open:split",
¦ "<up>": "nodePrev",
¦ "<down>": "nodeNext",
},
```

**Comment by weirongxu** [comment]
Are there any others? For example, `autocmd BufEnter, autocmd User CocNvimInit`

**Comment by wookayin** [comment]
Sorry there was actually a custom BufEnter I was forgetting, hidden somewhere.

```
autocmd WinEnter \[coc-explorer\]*   call timer_start(0, { -> coc#rpc#request('doKeymap', ['explorer-action-n-r'])})
```

It was working before until few weeks ago, and the `coc#rpc#request('doKeymap', ['explorer-action-n-r'])` call indeed causes the problem. I can get rid of this -- but do you have any suggestion about how I can manually invoke refresh commands?

I do see `<Plug>(coc-explorer-key-n-r)` are mapped to:
```
<Plug>(coc-explorer-key-n-r) * :<C-U>call coc#rpc#request('doKeymap', ['explorer-key-n-r'])<CR>
```

**Comment by weirongxu** [comment]
I think using `CocActionAsync` is enough

https://github.com/weirongxu/coc-explorer/wiki/Vim-API

```
auto WinEnter \[coc-explorer\]* call CocActionAsync('runCommand', 'explorer.doAction', 'closest', ['refresh'], [['relative', 0, 'file']])
```
