### ISSUE TITLE
Can't rename a file

### ISSUE THREAD

**Issue by VladPetryshyn** [weirongxu/coc-explorer#411]
## Hello! I am having some issues with renaming my file

NeoVim version: NVIM v0.5.0-dev

![image](https://user-images.githubusercontent.com/47623732/113482227-523acf80-94a6-11eb-85a2-0cafc41c6d38.png)

**Comment by weirongxu** [comment]
Can't reproduce, please update `coc.nvim` and `coc-explorer` to the latest version and provide output of `CocInfo` and `CocOpenLog`

**Comment by VladPetryshyn** [comment]
undefined## versions

vim version: NVIM v0.5.0-dev+1191-gf89bfa686
node version: v14.15.3
coc.nvim version: 0.0.80-2cece2600a
coc.nvim directory: /home/vlad/.vim/plugged/coc.nvim
term: screen-256color
platform: linux

## Log of coc.nvim

2021-04-04T17:26:43.887 INFO (pid:1146766) [plugin] - coc.nvim 0.0.80-2cece2600a initialized with node: v14.15.3 after 578ms
2021-04-04T17:26:50.513 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufWipeout', 1 ]
2021-04-04T17:26:50.515 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufWipeout', 1 ]
2021-04-04T17:26:50.748 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 3 ]
2021-04-04T17:26:50.750 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 3 ]
2021-04-04T17:26:55.148 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufWipeout', 4 ]
2021-04-04T17:26:55.148 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufWipeout', 4 ]
2021-04-04T17:26:56.305 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'explorer', '--focus' ]
2021-04-04T17:26:56.339 INFO (pid:1146766) [language-client-index] - eslint started with 1147731
2021-04-04T17:26:56.439 INFO (pid:1146766) [services] - registered service "tsserver"
2021-04-04T17:26:56.579 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 6 ]
2021-04-04T17:26:56.580 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 6 ]
2021-04-04T17:26:57.047 ERROR (pid:1146766) [node-client] - request error 0 on "nvim_call_function" [ 'coc_explorer#util#do_autocmd', [ 'CocExplorerOpenPost' ] ] Vim(call):E117: Неизвестная функция: <SNR>35_opened_explorer Error
    at WL.resumeNotification (/home/vlad/.vim/plugged/coc.nvim/build/index.js:21:1224)
    at tM.resumeNotification (/home/vlad/.vim/plugged/coc.nvim/build/index.js:23:4899)
    at Function.runAll (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:8077)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Ps (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:301:2546)
    at async Rr.open (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:321:51747)
    at async Hv.open (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:321:59274)
2021-04-04T17:26:57.934 INFO (pid:1146766) [attach] - receive notification: rename []
2021-04-04T17:26:57.941 ERROR (pid:1146766) [attach] - Notification error: rename [] Error: current buffer 6 not attached
    at AP.getCurrentState (/home/vlad/.vim/plugged/coc.nvim/build/index.js:247:562)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AP.rename (/home/vlad/.vim/plugged/coc.nvim/build/index.js:246:5700)
    at async LP.cocAction (/home/vlad/.vim/plugged/coc.nvim/build/index.js:247:11127)
    at async tM.<anonymous> (/home/vlad/.vim/plugged/coc.nvim/build/index.js:129:12652)
2021-04-04T17:27:01.341 INFO (pid:1146766) [attach] - receive notification: showInfo []
2021-04-04T17:27:01.436 INFO (pid:1146766) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]
2021-04-04T17:27:02.991 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'explorer', '--focus' ]
2021-04-04T17:27:07.644 WARN (pid:1146766) [events] - Handler of CursorHold blocked more than 2s: Error
    at dq.on (/home/vlad/.vim/plugged/coc.nvim/build/index.js:132:216)
    at new ZC (/home/vlad/.vim/plugged/coc.nvim/build/index.js:232:8131)
    at new AP (/home/vlad/.vim/plugged/coc.nvim/build/index.js:245:5586)
    at LP.init (/home/vlad/.vim/plugged/coc.nvim/build/index.js:247:10255)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async tM.<anonymous> (/home/vlad/.vim/plugged/coc.nvim/build/index.js:129:12117)
2021-04-04T17:27:35.045 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-04-04T17:27:41.074 INFO (pid:1146766) [watchman] - watchman watching project: /home/vlad/Документы/work/vv_new_front
2021-04-04T17:28:20.593 INFO (pid:1146766) [attach] - receive notification: runCommand [ 'explorer', '--focus' ]
2021-04-04T17:28:21.344 ERROR (pid:1146766) [node-client] - request error 0 on "nvim_call_function" [ 'coc_explorer#util#do_autocmd', [ 'CocExplorerOpenPost' ] ] Vim(call):E117: Неизвестная функция: <SNR>35_opened_explorer Error
    at WL.resumeNotification (/home/vlad/.vim/plugged/coc.nvim/build/index.js:21:1224)
    at tM.resumeNotification (/home/vlad/.vim/plugged/coc.nvim/build/index.js:23:4899)
    at Function.runAll (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:8077)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Ps (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:301:2546)
    at async Rr.open (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:321:51747)
    at async Hv.open (/home/vlad/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:321:59274)
2021-04-04T17:28:22.025 INFO (pid:1146766) [attach] - receive notification: rename []
2021-04-04T17:28:22.026 ERROR (pid:1146766) [attach] - Notification error: rename [] Error: current buffer 6 not attached
    at AP.getCurrentState (/home/vlad/.vim/plugged/coc.nvim/build/index.js:247:562)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AP.rename (/home/vlad/.vim/plugged/coc.nvim/build/index.js:246:5700)
    at async LP.cocAction (/home/vlad/.vim/plugged/coc.nvim/build/index.js:247:11127)
    at async tM.<anonymous> (/home/vlad/.vim/plugged/coc.nvim/build/index.js:129:12652)
2021-04-04T17:28:24.495 INFO (pid:1146766) [attach] - receive notification: showInfo []

**Comment by weirongxu** [comment]
Can you provide your steps to reproduce it? You don't seem to be using the coc-explorer rename feature, but the rename action for symbols of coc.nvim

**Comment by VladPetryshyn** [comment]
Sorry, you right, I accidentally was trying to rename it using the wrong keybindings
