### ISSUE TITLE
Git colors not showing in v0.17.1

### ISSUE THREAD

**Issue by petertriho** [weirongxu/coc-explorer#418]
Changes made in v0.17.1 seem to have broken git colors for me (works in v0.17.0)
CocInfo output:
```
## versions

vim version: NVIM v0.5.0-dev+nightly-554-g9471b1593
node version: v14.16.0
coc.nvim version: 0.0.80-ba262ef030
coc.nvim directory: /Users/peter/.local/share/nvim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-04-15T13:26:57.037 WARN (pid:50597) [attach] - Plugin not ready when received "highlight" []
2021-04-15T13:26:57.039 WARN (pid:50597) [attach] - Plugin not ready when received "runCommand" [ 'explorer', '--toggle', '--sources=file+' ]
2021-04-15T13:26:57.205 INFO (pid:50597) [services] - registered service "diagnostic-languageserver"
2021-04-15T13:26:57.299 ERROR (pid:50597) [node-client] - request error on "nvim_call_function" [
  'coc_explorer#highlight#extract_colors',
  [
    [
      'String',       'Character',
      'Number',       'Boolean',
      'Float',        'Identifier',
      'Function',     'Statement',
      'Conditional',  'Repeat',
      'Label',        'Operator',
      'Keyword',      'Exception',
      'PreProc',      'Include',
      'Define',       'Macro',
      'PreCondit',    'Type',
      'StorageClass', 'Structure',
      'Typedef',      'Special',
      'SpecialChar',  'Tag',
      'Delimiter',    'SpecialComment',
      'Debug',        'Todo'
    ]
  ]
] Vim:E117: Unknown function: coc_explorer#highlight#extract_colors Error
    at NeovimClient.request (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:10572:19)
    at NeovimClient.call (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:11709:19)
    at Hs (/Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:315:30266)
    at /Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:315:30634
    at x0.watchColorScheme (/Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:301:2973)
    at Object.<anonymous> (/Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:315:30595)
    at Module._compile (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:57603:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-04-15T13:26:57.300 ERROR (pid:50597) [node-client] - request error on "nvim_call_function" [ 'coc_explorer#highlight#extract_colors', [ [ 'Comment' ] ] ] Vim:E117: Unknown function: coc_explorer#highlight#extract_colors Error
    at NeovimClient.request (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:10572:19)
    at NeovimClient.call (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:11709:19)
    at Hs (/Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:315:30266)
    at /Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:321:27949
    at x0.watchColorScheme (/Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:301:2973)
    at Object.<anonymous> (/Users/peter/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:321:27886)
    at Module._compile (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:57603:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-04-15T13:26:57.398 INFO (pid:50597) [coc-git] - Looking for git in: git
2021-04-15T13:26:57.440 INFO (pid:50597) [services] - registered service "highlight"
2021-04-15T13:26:57.567 INFO (pid:50597) [language-client-index] - highlight started with 50726
2021-04-15T13:26:57.644 WARN (pid:50597) [attach] - Plugin not ready when received "runCommand" [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-04-15T13:26:57.697 INFO (pid:50597) [coc-tabnine] - Using tabnine from /Users/peter/.config/coc/extensions/coc-tabnine-data/binaries/3.3.108/x86_64-apple-darwin/TabNine
2021-04-15T13:26:57.723 INFO (pid:50597) [language-client-index] - cSpell started with 50727
2021-04-15T13:26:57.730 INFO (pid:50597) [plugin] - coc.nvim 0.0.80-ba262ef030 initialized with node: v14.16.0 after 680ms
2021-04-15T13:26:57.981 INFO (pid:50597) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-15T13:26:57.982 INFO (pid:50597) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 2 ]
2021-04-15T13:26:57.982 INFO (pid:50597) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 2 ]
2021-04-15T13:26:57.982 INFO (pid:50597) [attach] - receive notification: highlight []
2021-04-15T13:26:58.439 INFO (pid:50597) [attach] - receive notification: highlight []
2021-04-15T13:26:58.667 INFO (pid:50597) [attach] - receive notification: highlight []
2021-04-15T13:26:59.041 INFO (pid:50597) [attach] - receive notification: highlight []
2021-04-15T13:26:59.215 INFO (pid:50597) [attach] - receive notification: highlight []
2021-04-15T13:27:03.529 INFO (pid:50597) [attach] - receive notification: showInfo []
```

**Comment by petertriho** [comment]
Awesome thanks!
