### ISSUE TITLE
Coc-explorer does not update git status files after commit and push

### ISSUE THREAD

**Issue by ousatov-ua** [weirongxu/coc-explorer#435]
Hi!
Thanks for such a great explorer!

Currently, I observe the issue that files are still marked as changed or added/removed even after everything is commited or pushed. I'm using git-fugitibe
https://github.com/tpope/vim-fugitive

Maybe I miss some configuration? Explorer does not update its state even after running CocCommand `git.refresh`

**Comment by ousatov-ua** [comment]
The versions:
Coc-explorer = 0.17.5
Coc-git = 2.3.3
Git-fugitive = latest

**Comment by weirongxu** [comment]
Can you provide the `:CocInfo` messages? I can't reproduce this issue.

**Comment by weirongxu** [comment]
We use FugitiveChanged to detect Fugitive changes, I tested `Gadd` and `Git commit` on nvim 4.0 and the latest `Fugitive` but couldn't reproduce

**Comment by ousatov-ua** [comment]
Here are my steps:
1) :G <CR>
2) Press "-" opposite to files to stage
3) cc <CR>
4) Enter message, then  :x <CR>
5) Press "-" opposite to "Push"
6) Enter

**Comment by ousatov-ua** [comment]
I see next error:

```
2021-05-28T20:46:37.055 ERROR (pid:25568) [extension:coc-git] - exited with 1

2021-05-28T20:46:37.084 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-05-28T20:46:37.417 ERROR (pid:25568) [model-fetch] - Fetch error for https://api.github.com/repos/ousatov-ua/configs/issues?scope=all&per_page=100&page=1: {
  method: 'GET',
  hostname: 'api.github.com',
  port: 443,
  path: '/repos/ousatov-ua/configs/issues?scope=all&per_page=100&page=1',
  agent: null,
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  }
} Error: Bad response from https://api.github.com/repos/ousatov-ua/configs/issues?scope=all&per_page=100&page=1: 404
    at Ti.<anonymous> (/Users/alus/.config/nvim/plugged/coc.nvim/build/index.js:202:7204)
    at Ti.emit (events.js:315:20)
    at Ti._processResponse (/Users/alus/.config/nvim/plugged/coc.nvim/build/index.js:112:15139)
    at ClientRequest.Ti._onNativeResponse (/Users/alus/.config/nvim/plugged/coc.nvim/build/index.js:112:11137)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
2021-05-28T20:46:37.418 ERROR (pid:25568) [coc-git] - Request github issues error: Error: Bad response from https://api.github.com/repos/ousatov-ua/configs/issues?scope=all&per_page=100&page=1: 404
    at Ti.<anonymous> (/Users/alus/.config/nvim/plugged/coc.nvim/build/index.js:202:7204)
    at Ti.emit (events.js:315:20)
    at Ti._processResponse (/Users/alus/.config/nvim/plugged/coc.nvim/build/index.js:112:15139)
    at ClientRequest.Ti._onNativeResponse (/Users/alus/.config/nvim/plugged/coc.nvim/build/index.js:112:11137)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
2021-05-28T20:46:39.150 INFO (pid:25568) [completion-complete] - Results from: buffer,issues,word
2021-05-28T20:46:41.027 INFO (pid:25568) [completion-complete] - Results from: around,buffer,issues,syntax,word
2021-05-28T20:46:43.798 INFO (pid:25568) [attach] - receive request: CocAutocmd [ 'BufWritePre', 34 ]
2021-05-28T20:46:43.818 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 34 ]
2021-05-28T20:46:43.818 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 34 ]
2021-05-28T20:46:43.818 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufWipeout', 34 ]
2021-05-28T20:46:43.818 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufWipeout', 34 ]
2021-05-28T20:46:44.058 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'FugitiveChanged' ]
2021-05-28T20:46:44.881 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-05-28T20:47:13.475 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 33 ]
2021-05-28T20:47:13.475 INFO (pid:25568) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 33 ]
2021-05-28T20:47:17.479 INFO (pid:25568) [attach] - receive notification: showInfo []
```

**Comment by ousatov-ua** [comment]
I can push to that repo...

**Comment by ousatov-ua** [comment]
Seems like it tries to fetch issues, but I don't have any in my repo

**Comment by weirongxu** [comment]
I don't think the fetch error should affect the `coc-explorer` git status.
Your log is printing `FugitiveChange` and 
 `CocGitStatusChange`, which means that vim events should be triggered.

**Comment by ousatov-ua** [comment]
@weirongxu Yes, I see events. But buffer is not updated: it still shows colored marks (added lines, changed lines etc)...

**Comment by ousatov-ua** [comment]
The extension exited with -1:

ERROR (pid:25568) [extension:coc-git] - exited with 1

**Comment by weirongxu** [comment]
> @weirongxu Yes, I see events. But buffer is not updated: it still shows colored marks (added lines, changed lines etc)...

Oh? But it seems this is features of coc-git (If your means the added lines and changed lines in status-line)

**Comment by ousatov-ua** [comment]
Ha!  No, those are updated.
I just did next: removed all plugins and re-installed them.
And it works now: coc-explorer is updated.

Thanks!
