### ISSUE TITLE
Encountering an exception while I run `CocCommand explorer` first time

### ISSUE THREAD

**Issue by weiguoz** [weirongxu/coc-explorer#458]
Details: `[coc.nvim]: Uncaught exception: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`
It only occurs when I run the `CocCommand explorer`,  and it will be right when I run the command again.

`vim --version`
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul  5 2021 12:18:05)
macOS version - arm64
Included patches: 1-3107
```

**Comment by weirongxu** [comment]
I can't reproduce, please update `coc.nvim` and `coc-explorer` to the latest version and provide configuration of `coc-explorer` and output of `CocInfo`, `CocOpenLog`

**Comment by weiguoz** [comment]
## `CocConfig`

1. My configuration: https://github.com/weiguoz/zdots/blob/main/zdots/dotvim/vim/coc-settings.json#L63-L67
1. `coc-explorer` version: `v0.18.10`

## Output of `CocInfo`

```
  1 ## versions                                                                                                                                                             
  2                                                              
  3 vim version: VIM - Vi IMproved 8.2 8023107                   
  4 node version: v16.5.0                                        
  5 coc.nvim version: 0.0.80-19ead882b9                          
  6 coc.nvim directory: ~/.vim/plugged/coc.nvim      
  7 term: Apple_Terminal                                         
  8 platform: darwin                                             
  9                                                              
 10 ## Log of coc.nvim                                           
 11                                                              
 12 2021-07-18T20:51:27.213 INFO (pid:78100) [services] - registered service "languageserver.golang"
 13 2021-07-18T20:51:27.214 INFO (pid:78100) [services] - registered service "languageserver.clangd"
 14 2021-07-18T20:51:27.214 INFO (pid:78100) [services] - registered service "languageserver.bash"
 15 2021-07-18T20:51:27.261 INFO (pid:78100) [plugin] - coc.nvim 0.0.80-19ead882b9 initialized with node: v16.5.0 after 83ms
 16 2021-07-18T20:51:27.549 INFO (pid:78100) [attach] - receive notification: runCommand [ 'explorer' ]
 17 2021-07-18T20:51:27.583 INFO (pid:78100) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 2 ]
 18 2021-07-18T20:51:27.583 INFO (pid:78100) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 2 ]
 19 2021-07-18T20:51:27.615 ERROR (pid:78100) [server] - uncaughtException TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
 20     at ~/.vim/plugged/coc.nvim/build/index.js:30:1530
 21     at ~/.vim/plugged/coc.nvim/build/index.js:31:2679
 22     at vN.callback (~/.vim/plugged/coc.nvim/build/index.js:31:1330)
 23     at mN.<anonymous> (~/.vim/plugged/coc.nvim/build/index.js:31:2161)
 24     at mN.emit (node:events:394:28)                          
 25     at mN.parseData (~/.vim/plugged/coc.nvim/build/index.js:30:5651)
 26     at Interface.<anonymous> (~/.vim/plugged/coc.nvim/build/index.js:30:5259)
 27     at Interface.emit (node:events:394:28)                   
 28     at Interface._onLine (node:readline:487:10)              
 29     at Interface._normalWrite (node:readline:661:12)         
 30 2021-07-18T20:51:41.939 INFO (pid:78100) [attach] - receive notification: showInfo []
```

**Comment by yuzhen1024** [comment]
![2021-07-20 065248](https://user-images.githubusercontent.com/47154428/126237650-cd01ed61-6c22-4dfd-9ee1-3db9e1dfe581.jpg)
