### ISSUE TITLE
[BUG] Highlight broken

### ISSUE THREAD

**Issue by sainnhe** [weirongxu/coc-explorer#499]
**Describe the bug**

Highlight is broken, possibly caused by https://github.com/neoclide/coc.nvim/commit/7a2781f63d7230524077dca509998d0dd421a938 .

**Result from CocInfo**

```
## versions

vim version: NVIM v0.7.0-dev+896-g7085e5b0c8
node version: v17.3.0
coc.nvim version: 0.0.80-7a2781f63d
coc.nvim directory: /home/sainnhe/.local/share/nvim/plugins/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-01-17T10:03:16.179 INFO (pid:79235) [services] - registered service "diagnostic-languageserver"
2022-01-17T10:03:16.285 INFO (pid:79235) [coc-git] - Looking for git in: git
2022-01-17T10:03:16.297 INFO (pid:79235) [services] - registered service "highlight"
2022-01-17T10:03:16.872 INFO (pid:79235) [plugin] - coc.nvim initialized with node: v17.3.0 after 889ms
2022-01-17T10:03:16.903 INFO (pid:79235) [attach] - receive notification: highlight []
2022-01-17T10:03:16.909 INFO (pid:79235) [attach] - receive notification: runCommand [ 'explorer', '/home/sainnhe/.local/share/nvim/plugins/coc.nvim' ]
2022-01-17T10:03:16.988 INFO (pid:79235) [attach] - receive notification: runCommand [ 'git.refresh' ]
2022-01-17T10:03:17.117 INFO (pid:79235) [attach] - receive notification: doAutocmd [ 3 ]
2022-01-17T10:03:17.120 INFO (pid:79235) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_12_0_coc_helper_1',
  'BufDelete',
  3
]
2022-01-17T10:03:17.120 INFO (pid:79235) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_12_0_explorer_2',
  'BufDelete',
  3
]
2022-01-17T10:03:17.170 ERROR (pid:79235) [node-client] - request error 0 on "nvim_call_function" [
  'coc#highlight#ranges',
  [ 3, 2005, 'CocExplorerBufferExpandIcon', [ [Object] ] ]
] Vim(call):E5555: API call: Invalid ns_id Error
    at NvimTransport.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:10760:21)
    at NeovimClient2.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:11778:47)
    at Function.runAll (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:1:8639)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:325:45809
    at async ty.sync (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:325:39880)
    at async ir.open (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:325:45615)
    at async ny.open (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:325:55029)
2022-01-17T10:03:17.381 INFO (pid:79235) [attach] - receive notification: highlight []
2022-01-17T10:03:17.466 ERROR (pid:79235) [node-client] - request error 0 on "nvim_call_function" [
  'coc#highlight#ranges',
  [ 3, 2006, 'CocExplorerFileExpandIcon', [ [Object] ] ]
] Vim(call):E5555: API call: Invalid ns_id Error
    at NvimTransport.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:10760:21)
    at NeovimClient2.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:11778:47)
    at Function.runAll (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:1:8639)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:53535
    at async gh.runQueue (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:46584)
    at async Mi.sync (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:48247)
    at async Mi.renderPaths (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:53509)
    at async Bg.reload (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:305:25967)
    at async Bg.reloadDebounce (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:305:24874)
2022-01-17T10:03:17.726 ERROR (pid:79235) [node-client] - request error 0 on "nvim_call_function" [
  'coc#highlight#ranges',
  [ 3, 2005, 'CocExplorerBufferExpandIcon', [ [Object] ] ]
] Vim(call):E5555: API call: Invalid ns_id Error
    at NvimTransport.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:10760:21)
    at NeovimClient2.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:11778:47)
    at Function.runAll (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:1:8639)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async gh.runQueue (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:46584)
    at async Mi.sync (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:48247)
    at async Sk.load (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:26538)
    at async /home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:325:34379
    at async Object.invoke (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:304:1515)
2022-01-17T10:03:18.007 ERROR (pid:79235) [node-client] - request error 0 on "nvim_call_function" [
  'coc#highlight#ranges',
  [ 3, 2005, 'CocExplorerBufferExpandIcon', [ [Object] ] ]
] Vim(call):E5555: API call: Invalid ns_id Error
    at NvimTransport.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:10760:21)
    at NeovimClient2.resumeNotification (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:11778:47)
    at Function.runAll (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:1:8639)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async gh.runQueue (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:46584)
    at async Mi.sync (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:48247)
    at async Sk.load (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:319:26538)
    at async /home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:325:34488
    at async Object.invoke (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:304:1515)
2022-01-17T10:03:20.843 INFO (pid:79235) [attach] - receive notification: showInfo []
```

**Steps to reproduce**
1. execute `nvim`
2. `:CocExplorer ...`
3. See error

**Expected behavior**

![Screenshot_20220117_100618](https://user-images.githubusercontent.com/37491630/149689725-22299bbb-b04e-411d-96da-33706ace6448.png)

**Actual behavior**

![Screenshot_20220117_100432](https://user-images.githubusercontent.com/37491630/149689579-bcced1dd-1532-456d-a39c-c07f55f7f85c.png)

**Additional context**
None

**Comment by sainnhe** [comment]
Looks like not only the highlight, but the explorer contents are also broken.
