### ISSUE TITLE
Error when opening a file from coc-explorer: `UnhandledRejection: TypeError: Cannot read property 'bufnr' of null`

### ISSUE THREAD

**Issue by voldikss** [weirongxu/coc-explorer#78]
### To reproduce the issue
- Open nvim
- Open explorer(do not do anything before that)
- Move on to a file, Enter

Then I get 
```
[coc.nvim] error: UnhandledRejection: TypeError: Cannot read property 'bufnr' of null
```

### mini.vim
```vim
set rtp+=/path/to/coc.nvim
```

### output from `:CocOpenLog`
```log
2020-01-14T22:52:39.311 ERROR (pid:30883) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read property 'bufnr' of null
      at DocumentManager.<anonymous> (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4463:47)
      at Generator.next (<anonymous>)
      at /home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4038:71
      at new Promise (<anonymous>)
      at __awaiter (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4034:12)
      at DocumentManager.diffDocument (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4461:16)
      at Object.<anonymous> (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:157:27)
      at Generator.next (<anonymous>)
      at /home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:98:71
      at new Promise (<anonymous>)
} TypeError: Cannot read property 'bufnr' of null
    at DocumentManager.<anonymous> (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4463:47)
    at Generator.next (<anonymous>)
    at /home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4038:71
    at new Promise (<anonymous>)
    at __awaiter (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4034:12)
    at DocumentManager.diffDocument (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:4461:16)
    at Object.<anonymous> (/home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:157:27)
    at Generator.next (<anonymous>)
    at /home/voldikss/.config/coc/extensions/node_modules/coc-git/lib/index.js:98:71
    at new Promise (<anonymous>)
```

It seems coc-git threws that error. However I cannot figure it out.

I feel that this issue might only occurs on my machine. So if it cannot get reproduced, just ignore/close it.

**Comment by weirongxu** [comment]
Any configuration and `:CocInfo`? I did not reproduce in mini_vimrc.

**Comment by voldikss** [comment]
`:CocInfo` doesn't have something helpful, except an error message
```log
## versions

vim version: NVIM v0.5.0-fa9b057
node version: v12.14.0
coc.nvim version: 0.0.74
term: xterm-256color
platform: linux

## Messages
[coc.nvim] error: UnhandledRejection: TypeError: Cannot read property 'bufnr' of null
## Output channel: explorer


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
> git ls-files -- mini.vim
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- mini.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- mini.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- mini.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- mini.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /home/voldikss/dotfiles
resolved root: /home/voldikss/dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- mini.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
```

**Comment by voldikss** [comment]
Let me close it as this might be caused by other things.

**Comment by voldikss** [comment]
This should be fixed by coc-git, related https://github.com/neoclide/coc.nvim/issues/1278
